ttcrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),
]

ttcrm/ttcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, contacts, mail, chat, phone
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('contacts/', contacts, name='contacts'),
    path('phone/', phone, name='phone'),
    path('mail/', mail, name='mail'),
    path('chat/', chat, name='chat'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttcrm/lead/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Низкий'),
        (MEDIUM, 'Средний'),
        (HIGH, 'Высокий'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'Новый'),
        (CONTACTED, 'Связался'),
        (WON, 'Сделка'),
        (LOST, 'Потерян'),
    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, null=True)
    email = models.EmailField()
    address = models.CharField(max_length=255, null=True)
    contact_person = models.CharField(max_length=255, null=True)
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='leadfiles')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username


class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

ttcrm/lead/forms.py
from django import forms

from .models import Lead, Comment, LeadFile


class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status',)


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)

ttcrm/lead/views.py
import csv

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView

from .forms import AddCommentForm, AddFileForm
from .models import Lead

from client.models import Client, Comment as ClientComment


@login_required
def leads_export(request):
    leads = Lead.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="leads.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(['Лид', 'Контактное лицо', 'Телефон', 'e-mail', 'Адрес', 'Описание', 'Дата создания', 'Автор'])

    for lead in leads:
        writer.writerow([lead.name, lead.contact_person, lead.phone, lead.email, lead.address, lead.description, lead.created_at, lead.created_by])

    return response


class LeadListView(LoginRequiredMixin, ListView):
    model = Lead

    def get_queryset(self):
        queryset = super(LeadListView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, converted_to_client=False)


class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()
        context['fileform'] = AddFileForm()

        return context

    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


class LeadDeleteView(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')

    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class LeadUpdateView(LoginRequiredMixin, UpdateView):
    model = Lead
    fields = ('name', 'contact_person', 'phone', 'email', 'address', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактировать лид'

        return context

    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    fields = ('name', 'contact_person', 'phone', 'email', 'address', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['team'] = self.request.user.userprofile.active_team
        context['title'] = 'Добавить лид'

        return context

    def form_valid(self, form):

        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = self.request.user.userprofile.active_team
        self.object.save()

        return redirect(self.get_success_url())


class AddFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = self.request.user.userprofile.active_team
            file.lead_id = pk
            file.created_by = request.user
            file.save()
        return redirect('leads:detail', pk=pk)


class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = self.request.user.userprofile.active_team
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)


class ConvertToClientView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
        team = self.request.user.userprofile.active_team

        client = Client.objects.create(
            name=lead.name,
            contact_person=lead.contact_person,
            phone=lead.phone,
            email=lead.email,
            address=lead.address,
            description=lead.description,
            created_by=request.user,
            team=self.request.user.userprofile.active_team,
        )

        lead.converted_to_client = True
        lead.save()

        # Convert lead comments to client comments

        comments = lead.comments.all()

        for comment in comments:
            ClientComment.objects.create(
                client=client,
                content=comment.content,
                created_by=comment.created_by,
                team=team
            )

        # Show message and redirect

        messages.success(request, 'Лид преобразован в клиента.')

        return redirect('leads:list')

ttcrm/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ lead.name }}</h1>

        {% if lead.contact_person or lead.phone or lead.address %}
            <div class="mb-6">
                <p class="font-semibold">Контакты:</p>
                {% if lead.contact_person %}
                    <p class="">Контактное лицо: {{ lead.contact_person }}</p>
                {% endif %}
                {% if lead.phone %}
                    <p class="mb-2">Телефон: {{ lead.phone }}</p>
                {% endif %}
                {% if lead.address %}
                    <p class="">Адрес: {{ lead.address }}</p>
                {% endif %}
            </div>
        {% endif %}

        {% if lead.description %}
            <div class="mb-6">
                <p class="font-semibold">Описание</p>
                <p class="mb-2">{{ lead.description }}</p>
            </div>
        {% endif %}

        <p class="font-semibold">Приоритет</p>
        <p class="mb-2">{{ lead.get_priority_display }}</p>

        <p class="font-semibold">Статус</p>
        <p class="mb-2">{{ lead.get_status_display }}</p>

        <p class="font-semibold">Создан</p>
        <p class="mb-2">{{ lead.created_at|date:"d M Y, H:i" }}</p>

        <p class="font-semibold">Изменен</p>
        <p class="mb-6">{{ lead.modified_at|date:"d M Y" }}</p>

        <hr class="my-4">

        <form id="lead_delete_form" method="post" action="{% url 'leads:delete' lead.id %}">
            {% csrf_token %}
        </form>

        <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Преобразовать в клиента</a>
        <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Изменить</a>
        <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="py-2 px-4 rounded-xl bg-red-500 text-white">Удалить</a>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Комментарии</h2>

        <div class="space-y-4">
            {% for comment in lead.comments.all %}
                <div class="bg-gray-200 mb-2 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by.first_name }} {{ comment.created_by.last_name }}</strong> @ {{ comment.created_at }}</p>
                    {{ comment.content }}
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'leads:add_comment' lead.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Сохранить комментарий</button>
        </form>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Файлы</h2>

        <div class="space-y-4">
            {% for file in lead.files.all %}
                <div class="bg-gray-200 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>
                    <a href="{{ file.file.url }}">Скачать</a>
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'leads:add_file' lead.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ fileform.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Загрузить файл</button>
        </form>

        <hr class="my-4">

        <a href="{% url 'leads:list' %}">Вернуться к списку Лидов</a>
    </div>
{% endblock %}

ttcrm/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">{{ title }}</h1>

        {% if team.plan.max_leads > team.leads.count or title == 'Редактировать лид' %}
            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Сохранить</button>
            </form>
        {% else %}
            <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
                Ваша команда достигла максимального числа потенциальных клиентов. Вам нужно обновить тарифный план!
            </div>
        {% endif %}
    </div>
{% endblock %}

ttcrm/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Лиды{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">Лиды</h1>
        <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Добавить Лид</a>
        <a href="{% url 'leads:export' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 text-white">Экспорт Лидов</a>

        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Название</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Приоритет</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
            </div>

            {% for lead in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'leads:detail' lead.id %}">{{ lead.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">В базе пока нет потенциальных клиентов...</p>
        {% endif %}
    </div>
{% endblock %}