ttcrm/client/urls.py
from django.urls import path

from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('add/', views.clients_add, name='add'),
    path('export/', views.clients_export, name='export'),

]

ttcrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),
]

ttcrm/ttcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, contacts, mail, chat, phone
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('contacts/', contacts, name='contacts'),
    path('phone/', phone, name='phone'),
    path('mail/', mail, name='mail'),
    path('chat/', chat, name='chat'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttcrm/client/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, null=True)
    email = models.EmailField()
    address = models.CharField(max_length=255, null=True)
    contact_person = models.CharField(max_length=255, null=True)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username


class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

ttcrm/client/forms.py
from django import forms

from .models import Client, Comment, ClientFile


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'contact_person', 'phone', 'email', 'address', 'description',)


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

ttcrm/client/views.py
import csv

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .forms import AddClientForm, AddCommentForm, AddFileForm
from .models import Client

from team.models import Team


@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="clients.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(['Клиент', 'Описание', 'Дата создания', 'Автор'])

    for client in clients:
        writer.writerow([client.name, client.description, client.created_at, client.created_by])

    return response


@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user)

    return render(request, 'client/clients_list.html', {
        'clients': clients
    })


@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.client_id = pk
            file.created_by = request.user
            file.save()

            return redirect('clients:detail', pk=pk)
    return redirect('clients:detail', pk=pk)


@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect('clients:detail', pk=pk)
    else:
        form = AddCommentForm()

    return render(request, 'client/clients_detail.html', {
        'client': client,
        'form': form,
        'fileform': AddFileForm(),
    })


@login_required
def clients_add(request):
    team = request.user.userprofile.active_team

    if request.method == 'POST':
        form = AddClientForm(request.POST)

        if form.is_valid():

            client = form.save(commit=False)
            client.created_by = request.user
            client.team = request.user.userprofile.active_team
            client.save()

            messages.success(request, 'Клиент создан.')

            return redirect('clients:list')
    else:
        form = AddClientForm()

    return render(request, 'client/clients_add.html', {
        'form': form,
        'team': team
    })


@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()

            messages.success(request, 'Изменения сохранены.')

            return redirect('clients:list')
    else:
        form = AddClientForm(instance=client)

    return render(request, 'client/clients_edit.html', {
        'form': form
    })


@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, 'Клиент был удален.')

    return redirect('clients:list')

ttcrm/client/templates/client/clients_add.html
{% extends 'core/base.html' %}

{% block title %}Добавить клиента{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Добавить клиента</h1>

        {% if team.plan.max_clients > team.clients.all|length %}
            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Создать</button>
            </form>
        {% else %}
            <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
                Ваша команда достигла максимального числа клиентов. Вам нужно обновить тарифный план!
            </div>
        {% endif %}
    </div>
{% endblock %}

ttcrm/client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ client.name }}</h1>

        {% if client.description %}
            <p class="font-semibold">Описание</p>
            <p class="mb-2">{{ client.description }}</p>
        {% endif %}

        <p class="font-semibold">Создан</p>
        <p class="mb-2">{{ client.created_at|date:"d M Y, H:i" }}</p>

        <p class="font-semibold">Изменен</p>
        <p class="mb-6">{{ client.modified_at|date:"d M Y" }}</p>

        <hr class="my-4">
        <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Изменить</a>
        <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Удалить</a>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Комментарии</h2>

        <div class="space-y-4">
            {% for comment in client.comments.all %}
                <div class="bg-gray-200 mb-2 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
                    {{ comment.content }}
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'clients:add_comment' client.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Сохранить комментарий</button>
        </form>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Файлы</h2>

        <div class="space-y-4">
            {% for file in client.files.all %}
                <div class="bg-gray-200 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>
                    <a href="{{ file.file.url }}">Скачать</a>
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'clients:add_file' client.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ fileform.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Загрузить файл</button>
        </form>

        <hr class="my-4">

        <a href="{% url 'clients:list' %}">Вернуться к списку клиентов</a>
    </div>
{% endblock %}

ttcrm/client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}Редактирование Клиента{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Редактирование Клиента</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Сохранить</button>
        </form>
    </div>
{% endblock %}

ttcrm/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %}Клиенты{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">Клиенты</h1>
        <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Добавить клиента</a>
        <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 text-white">Экспорт клиентов</a>

        {% if clients %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Название</p>
            </div>

            {% for client in clients %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">В базе пока нет клиентов...</p>
        {% endif %}
    </div>
{% endblock %}