ttcrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),
]

ttcrm/team/urls.py
from django.urls import path

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.teams_list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/activate/', views.teams_activate, name='activate'),
]

ttcrm/ttcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, contacts, mail, chat, phone
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('contacts/', contacts, name='contacts'),
    path('phone/', phone, name='phone'),
    path('mail/', mail, name='mail'),
    path('chat/', chat, name='chat'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttcrm/userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('myaccount/', views.myaccount, name='myaccount'),
    path('sign-up/', views.signup, name='signup'),
]

ttcrm/userprofile/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    active_team = models.ForeignKey(Team, related_name='userprofile', blank=True, null=True, on_delete=models.CASCADE)

ttcrm/userprofile/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

INPUT_CLASS = 'w-full my-4 py-4 px-6 rounded-xl bg-gray-200'


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите логин',
        'class': INPUT_CLASS
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль',
        'class': INPUT_CLASS
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': INPUT_CLASS
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': INPUT_CLASS
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': INPUT_CLASS
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': INPUT_CLASS
    }))

ttcrm/userprofile/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import SignupForm
from .models import Userprofile

from team.models import Team


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save()

            team = Team.objects.create(name='Название команды', created_by=user)
            team.members.add(user)
            team.save()

            Userprofile.objects.create(user=user, active_team=team)

            return redirect('/log-in/')
    else:
        form = SignupForm()

    return render(request, 'userprofile/signup.html', {
        'form': form
    })


@login_required
def myaccount(request):
    return render(request, 'userprofile/myaccount.html')

ttcrm/userprofile/templates/userprofile/login.html
{% extends 'core/base.html' %}

{% block title %}Войти{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-6 text-xl">Войти</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="mt-6 py-4 px-8 bg-teal-500 text-white rounded-xl">Войти</button>
        </form>
    </div>
{% endblock %}

ttcrm/userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %}
{% block title %}Мой аккаунт{% endblock %}
{% block content %}
<div class="py-6 px-6">
    <h1 class="mb-6 text-xl">Мой аккаунт</h1>

    <p class="mb-2">
        <strong>Пользователь: </strong>
        {% if request.user.first_name or request.user.last_name %}
            {{ request.user.first_name }} {{ request.user.last_name }}
        {% else %}
            {{ request.user.username }}
        {% endif %}
    </p>

    <p class="mb-2">
        {% if active_team %}
            <strong>Команда: </strong><a href="{% url 'team:detail' active_team.id %}">{{ active_team.name }}</a>

            {% if active_team.created_by == request.user %}
                <a href="{% url 'team:edit' active_team.id %}"> (Редактировать)</a>
            {% endif %}
        {% else %}
            <a href="{% url 'team:list' %}">Выбрать команду</a>
        {% endif %}
    </p>

    <hr class="mb-4">

    <a href="{% url 'logout' %}" class="inline-block py-4 px-6 bg-red-600 rounded-xl text-white">Выход</a>
</div>
{% endblock %}

ttcrm/userprofile/templates/userprofile/signup.html
{% extends 'core/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="mb-6 text-xl">Регистрация</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Отправить</button>
    </form>
</div>
{% endblock %}